name: Builder

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build App
      run: CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w" -o promcasa
      
    - name: Compress App
      run: |
        strip promcasa
        upx promcasa
        
    - name: Get Version Tag
      run: |
         echo TAG_NAME=$(cat version.go | grep VERSION | awk -F'"' '{print $2}') >> $GITHUB_ENV
         
    - name: Get Time Tag
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
        
    - name: NFPM DEB
      if: github.event_name != 'pull_request'
      uses: skynet-core/nfpm@v1.4
      id: deb-package
      env:
        VERSION: ${{ env.TAG_NAME }}
      with:
       target: promcasa_v${{ env.TAG_NAME }}.deb
       config: "examples/promcasa.yml"
       packager: "deb"
       
    - name: NFPM RPM
      if: github.event_name != 'pull_request'
      uses: skynet-core/nfpm@v1.4
      id: rpm-package
      env:
        VERSION: ${{ env.TAG_NAME }}
      with:
       target: promcasa_v${{ env.TAG_NAME }}.rpm
       config: "examples/promcasa.yml"
       packager: "rpm"
        
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            promcasa
            promcasa_v${{ env.TAG_NAME }}.deb
            promcasa_v${{ env.TAG_NAME }}.rpm
        tag_name: v${{ steps.time.outputs.time }}
        release_name: promcasa_v${{ env.TAG_NAME }}_${{ steps.time.outputs.time }}
        draft: false
        prerelease: false
        overwrite: true
